package com.fgl.eai.iib.testing

import groovy.xml.XmlUtil
import spock.lang.Unroll

/**
 * Transaction integration test which uses the Spock framework (https://code.google.com/p/spock/) to test different transaction scenarios for trx-sales-xbr-subscriber-fgl IIB component
 * Specifically puts sample ARTS XML messages on the input queue and checks CSV string response which is returned from XBR IIB subscriber
 * @author wrhett
 *
 */
class TestXBRTransactionSubscriberSpecification extends BaseSpecification {

    // used by each test
    String transactionNumber
    def jira
    def scenarioDesc
    def scenarioNum
    def iibInputXMLFile
    def iibInputXMLFileFull
    def iibOutputFile
    def iibOutputFileFull
    def response

    @Unroll("Testing JIRA #jira - scenario #scenarioNum - #scenarioDesc - Transaction number #transactionNumber in trx-sales-aw-subscriber-fgl output matches expected file #iibInputXMLFile")
    def "Read XML from IIB response and assert the data is valid"() {

        setup:

        // input and expected result files are within this project
        iibInputXMLFileFull = "./source/trx-sales-all-samples-fgl/arts/${iibInputXMLFile}"
        iibOutputFileFull = "./source/trx-sales-all-samples-fgl/tlog/${iibOutputFile}"

        when: "A message is put on the IIB input queue"

        // read the iib input file
        String inputMessage = XmlUtil.serialize(new XmlSlurper().parse(iibInputXMLFileFull))
        println("Putting a message on the queue")
        // send the message to IIB with the test header set and a temporary reply queue created so IIB can response back
        response = producer.requestBodyAndHeader("jms:$inputQueue?deliveryPersistent=false&exchangePattern=InOut&requestTimeout=90000&asyncConsumer=true&asyncStartListener=true&replyToType=Shared", inputMessage, 'TestingHeader', 'True', String.class)

        then: "Message on reply queue matches expected results"

        println("Raw response output ${response}")

        if (!response)
            throw new Exception("No response from IIB")


        def formatTLOG = {
            it.replaceAll("\\r","") // remove any carriage returns
                    .tokenize( '\n' )    // tokenize to a list (1 string per line)
                    .collect{it.trim()}  // trim each line to remove any trailing whitespace
        }

        // parse the expected output contained in the file
        def expected = formatTLOG(new File(iibOutputFileFull).text)

        def formattedResponse=formatTLOG(response)

        /// we are comparing 2 lists (the tokenize did this)
        assert expected==formattedResponse


        where:
        // Spock data table, each row becomes a new test
        jira               | scenarioNum  | scenarioDesc                                                                                                                    | transactionNumber           | iibInputXMLFile                                                                                                                    | iibOutputFile

        "FPOE-13063"       | "1"         | "XBR Basic Sale"                                                                                                                 | "000004"                    | 'FPOE-13063-1.xml'                                                                                                                 | 'FPOE-13063-1.csv'
        "FPOE-13063"       | "2"         | "Cash Sale with Penny Round Up with data"                                                                                        | "1826"                      | 'Cash Sale with Penny Round Up with data.xml'                                                                                      | 'Cash Sale with Penny Round Up with data.txt'

        // added 12/28 based on Piyush samples he had already tested
        "FPOE-13063"       | "3"         | "Enhanced Sale with Data"                                                                                                        | "8980"                      | 'Enhanced Sale with Data.xml'                                                                                                      | 'Enhanced Sale with Data.txt'
        "FPOE-13063"       | "4"         | "GiftCard Tendered with data"                                                                                                    | "1826"                      | 'GiftCard Tendered with data.xml'                                                                                                  | 'GiftCard Tendered with data.txt'
        "FPOE-13063"       | "5"         | "Cash Sale with Penny Round down with data"                                                                                      | "1826"                      | 'Cash Sale with Penny Round down with data.xml'                                                                                    | 'Cash Sale with Penny Round down with data.txt'
        "FPOE-13063"       | "6"         | "Control TransactionVoid Auto Void with data"                                                                                    | "1826"                      | 'Control TransactionVoid Auto Void with data.xml'                                                                                  | 'Control TransactionVoid Auto Void with data.txt'
        "FPOE-13063"       | "7"         | "Charge Sale with data"                                                                                                          | "2082"                      | 'Charge Sale with data.xml'                                                                                                        | 'Charge Sale with data.txt'
        "FPOE-13063"       | "8"         | "Cheque Tendered with data"                                                                                                      | "1826"                      | 'Cheque Tendered with data.xml'                                                                                                    | 'Cheque Tendered with data.txt'
        "FPOE-13063"       | "9"         | "Competitor Name Note Type SubTotal Discount with Approval"                                                                      | "8980"                      | 'Competitor Name Note Type SubTotal Discount with Approval.xml'                                                                    | 'Competitor Name Note Type SubTotal Discount with Approval.txt'
        "FPOE-13063"       | "10"        | "Competitor Name Note Type with Data"                                                                                            | "8980"                      | 'Competitor Name Note Type with Data.xml'                                                                                          | 'Competitor Name Note Type with Data.txt'
        "FPOE-13063"       | "11"        | "Control NoSale with data"                                                                                                       | "1826"                      | 'Control NoSale with data.xml'                                                                                                     | 'Control NoSale with data.txt'
        "FPOE-13063"       | "12"        | "Control OperatorSignOff with data"                                                                                              | "1826"                      | 'Control OperatorSignOff with data.xml'                                                                                            | 'Control OperatorSignOff with data.txt'
        "FPOE-13063"       | "13"        | "Control OperatorSignOn with data"                                                                                               | "1826"                      | 'Control OperatorSignOn with data.xml'                                                                                             | 'Control OperatorSignOn with data.txt'
        "FPOE-13063"       | "14"        | "Control TransactionVoid with dataa"                                                                                             | "1826"                      | 'Control TransactionVoid with data.xml'                                                                                            | 'Control TransactionVoid with data.txt'
        "FPOE-13063"       | "15"        | "Control Unsettled with data"                                                                                                    | "1826"                      | 'Control Unsettled with data.xml'                                                                                                  | 'Control Unsettled with data.txt'
        "FPOE-13063"       | "16"        | "Control XRead with data"                                                                                                        | "1826"                      | 'Control XRead with data.xml'                                                                                                      | 'Control XRead with data.txt'
        "FPOE-13063"       | "17"        | "Control ZRead with data"                                                                                                        | "1826"                      | 'Control ZRead with data.xml'                                                                                                      | 'Control ZRead with data.txt'
        "FPOE-13063"       | "18"        | "Coupon and VisaTendered with data"                                                                                              | "1826"                      | 'Coupon and VisaTendered with data.xml'                                                                                            | 'Coupon and VisaTendered with data.txt'
        "FPOE-13063"       | "19"        | "CreditDebit Visa Tendered with data"                                                                                            | "1826"                      | 'CreditDebit Visa Tendered with data.xml'                                                                                          | 'CreditDebit Visa Tendered with data.txt'
        "FPOE-13063"       | "20"        | "DealGroup Discount with Data"                                                                                                   | "2677"                      | 'DealGroup Discount with Data.xml'                                                                                                 | 'DealGroup Discount with Data.txt'
        "FPOE-13063"       | "21"        | "Discount BOGO plus Temporary Price with data"                                                                                   | "2741"                      | 'Discount BOGO plus Temporary Price with data.xml'                                                                                 | 'Discount BOGO plus Temporary Price with data.txt'
        "FPOE-13063"       | "22"        | "Discount BOGO Set Price with data"                                                                                              | "2741"                      | 'Discount BOGO Set Price with data.xml'                                                                                            | 'Discount BOGO Set Price with data.txt'
        "FPOE-13063"       | "23"        | "Discount BOGO with data"                                                                                                        | "2618"                      | 'Discount BOGO with data.xml'                                                                                                      | 'Discount BOGO with data.txt'
        "FPOE-13063"       | "24"        | "Employee Non Verifed Return with data"                                                                                          | "2522"                      | 'Employee Non Verifed Return with data.xml'                                                                                        | 'Employee Non Verifed Return with data.txt'
        "FPOE-13063"       | "25"        | "Employee Non-Receipted Return with data"                                                                                        | "2522"                      | 'Employee Non-Receipted Return with data.xml'                                                                                      | 'Employee Non-Receipted Return with data.txt'
        "FPOE-13063"       | "26"        | "Employee Receipted Return with data"                                                                                            | "2522"                      | 'Employee Receipted Return with data.xml'                                                                                          | 'Employee Receipted Return with data.txt'
        "FPOE-13063"       | "27"        | "Employee Sale and Return with data"                                                                                             | "2522"                      | 'Employee Sale and Return with data.xml'                                                                                           | 'Employee Sale and Return with data.txt'
        "FPOE-13063"       | "28"        | "Employee Sale with Data"                                                                                                        | "8980"                      | 'Employee Sale with Data.xml'                                                                                                      | 'Employee Sale with Data.txt'
        "FPOE-13063"       | "29"        | "Exchange Transaction with Exemptions on Original Sale and No Tax Exemption on New Sale"                                         | "9992"                      | 'Exchange Transaction with Exemptions on Original Sale and No Tax Exemption on New Sale.xml'                                       | 'Exchange Transaction with Exemptions on Original Sale and No Tax Exemption on New Sale.txt'
        "FPOE-13063"       | "30"        | "Exchange Transaction with Item and Transaction Tax Exemptions on Original Sale and Transaction Tax Exemption on New Sale"       | "9994"                      | 'Exchange Transaction with Item and Transaction Tax Exemptions on Original Sale and Transaction Tax Exemption on New Sale.xml'     | 'Exchange Transaction with Item and Transaction Tax Exemptions on Original Sale and Transaction Tax Exemption on New Sale.txt'
        "FPOE-13063"       | "31"        | "Exchange Transaction with Item Tax Exemption on Original Sale and Transaction Tax Exemption on New Sale"                        | "9995"                      | 'Exchange Transaction with Item Tax Exemption on Original Sale and Transaction Tax Exemption on New Sale.xml'                      | 'Exchange Transaction with Item Tax Exemption on Original Sale and Transaction Tax Exemption on New Sale.txt'
        "FPOE-13063"       | "32"        | "Exchange Transaction with No Tax Exemptions on Original Sale and Tax Exemption on New Sale"                                     | "9991"                      | 'Exchange Transaction with No Tax Exemptions on Original Sale and Tax Exemption on New Sale.xml'                                   | 'Exchange Transaction with No Tax Exemptions on Original Sale and Tax Exemption on New Sale.txt'
        "FPOE-13063"       | "33"        | "Exchange Transaction with Tax Exemptions on Return and Sale"                                                                    | "9990"                      | 'Exchange Transaction with Tax Exemptions on Return and Sale.xml'                                                                  | 'Exchange Transaction with Tax Exemptions on Return and Sale.txt'
        "FPOE-13063"       | "34"        | "LineVoid with data"                                                                                                             | "1826"                      | 'LineVoid with data.xml'                                                                                                           | 'LineVoid with data.txt'
        "FPOE-13063"       | "35"        | "MallGiftCertificate and cash Tendered with data"                                                                                | "1826"                      | 'MallGiftCertificate and cash Tendered with data.xml'                                                                              | 'MallGiftCertificate and cash Tendered with data.txt'
        "FPOE-13063"       | "36"        | "Manual GovernmentTax Exemption with data"                                                                                       | "2504"                      | 'Manual GovernmentTax Exemption with data.xml'                                                                                     | 'Manual GovernmentTax Exemption with data.txt'
        "FPOE-13063"       | "37"        | "Manual Item Discount with Approval with Data"                                                                                   | "8980"                      | 'Manual Item Discount with Approval with Data.xml'                                                                                 | 'Manual Item Discount with Approval with Data.txt'
        "FPOE-13063"       | "38"        | "Manual Item Discount with Data"                                                                                                 | "8980"                      | 'Manual Item Discount with Data.xml'                                                                                               | 'Manual Item Discount with Data.txt'
        "FPOE-13063"       | "39"        | "Manual Item Mark Up with Approval with Data"                                                                                    | "8980"                      | 'Manual Item Mark Up with Approval with Data.xml'                                                                                  | 'Manual Item Mark Up with Approval with Data.txt'
        "FPOE-13063"       | "40"        | "Manual Native Tax Exemption Shipping Ref Number with data"                                                                      | "2504"                      | 'Manual Native Tax Exemption Shipping Ref Number with data.xml'                                                                    | 'Manual Native Tax Exemption Shipping Ref Number with data.txt'
        "FPOE-13063"       | "41"        | "Manual Native Tax Exemption with data"                                                                                          | "2504"                      | 'Manual Native Tax Exemption with data.xml'                                                                                        | 'Manual Native Tax Exemption with data.txt'
        "FPOE-13063"       | "42"        | "Manual Non Native Tax Exemption with data"                                                                                      | "2504"                      | 'Manual Non Native Tax Exemption with data.xml'                                                                                    | 'Manual Non Native Tax Exemption with data.txt'
        "FPOE-13063"       | "43"        | "Mark Up and Discount in Same Transaction with data"                                                                             | "000014"                    | 'Mark Up and Discount in Same Transaction with data.xml'                                                                           | 'Mark Up and Discount in Same Transaction with data.txt'
        "FPOE-13063"       | "44"        | "Multiple ItemTax Exemptions Federal and Provincial with data"                                                                   | "2504"                      | 'Multiple ItemTax Exemptions Federal and Provincial with data.xml'                                                                 | 'Multiple ItemTax Exemptions Federal and Provincial with data.txt'
        "FPOE-13063"       | "45"        | "Multiple Tax Exemptions both System and Manual"                                                                                 | "8937"                      | 'Multiple Tax Exemptions both System and Manual.xml'                                                                               | 'Multiple Tax Exemptions both System and Manual.txt'
        "FPOE-13063"       | "46"        | "Multiple TransactionTax Exemptions Federal and Provincial with data"                                                            | "2504"                      | 'Multiple TransactionTax Exemptions Federal and Provincial with data.xml'                                                          | 'Multiple TransactionTax Exemptions Federal and Provincial with data.txt'
        "FPOE-13063"       | "47"        | "Non Receipted Return with data"                                                                                                 | "2522"                      | 'Non Receipted Return with data.xml'                                                                                               | 'Non Receipted Return with data.txt'
        "FPOE-13063"       | "48"        | "Non Verified Return with data"                                                                                                  | "2522"                      | 'Non Verified Return with data.xml'                                                                                                | 'Non Verified Return with data.txt'
        "FPOE-13063"       | "49"        | "PayIn TenderControlTransacation with data"                                                                                      | "2069"                      | 'PayIn TenderControlTransacation with data.xml'                                                                                    | 'PayIn TenderControlTransacation with data.txt'
        "FPOE-13063"       | "50"        | "PayOut TenderControlTransaction with data"                                                                                      | "2073"                      | 'PayOut TenderControlTransaction with data.xml'                                                                                    | 'PayOut TenderControlTransaction with data.txt'
        "FPOE-13063"       | "51"        | "Price Change from 0 with Approval with Data"                                                                                    | "8980"                      | 'Price Change from 0 with Approval with Data.xml'                                                                                  | 'Price Change from 0 with Approval with Data.txt'
        "FPOE-13063"       | "52"        | "Receipted Return to Charge Tender with data"                                                                                    | "2522"                      | 'Receipted Return to Charge Tender with data.xml'                                                                                  | 'Receipted Return to Charge Tender with data.txt'
        "FPOE-13063"       | "53"        | "Receipted Return with data"                                                                                                     | "2522"                      | 'Receipted Return with data.xml'                                                                                                   | 'Receipted Return with data.txt'
        "FPOE-13063"       | "54"        | "Receipted Return with Item Tax Exemption on Original Sale"                                                                      | "9993"                      | 'Receipted Return with Item Tax Exemption on Original Sale.xml'                                                                    | 'Receipted Return with Item Tax Exemption on Original Sale.txt'
        "FPOE-13063"       | "55"        | "Receipted Return with Transaction Federal Tax Exemption on Original Sale"                                                       | "2522"                      | 'Receipted Return with Transaction Federal Tax Exemption on Original Sale.xml'                                                     | 'Receipted Return with Transaction Federal Tax Exemption on Original Sale.txt'
        "FPOE-13063"       | "56"        | "Return with Retail Price Modifier discount data"                                                                                | "2522"                      | 'Return with Retail Price Modifier discount data.xml'                                                                              | 'Return with Retail Price Modifier discount data.txt'
        "FPOE-13063"       | "57"        | "SCENE Points Earned and Redeemed with different cards"                                                                          | "1826"                      | 'SCENE Points Earned and Redeemed with different cards.xml'                                                                        | 'SCENE Points Earned and Redeemed with different cards.txt'
        "FPOE-13063"       | "58"        | "SCENE Points Earned with data"                                                                                                  | "1826"                      | 'SCENE Points Earned with data.xml'                                                                                                | 'SCENE Points Earned with data.txt'
        "FPOE-13063"       | "59"        | "SCENE Points Redeemed with data"                                                                                                | "1826"                      | 'SCENE Points Redeemed with data.xml'                                                                                              | 'SCENE Points Redeemed with data.txt'
        "FPOE-13063"       | "60"        | "SCENE Return as Tender with data"                                                                                               | "2522"                      | 'SCENE Return as Tender with data.xml'                                                                                             | 'SCENE Return as Tender with data.txt'
        "FPOE-13063"       | "61"        | "SCENE Return decrementing points with data"                                                                                     | "2522"                      | 'SCENE Return decrementing points with data.xml'                                                                                   | 'SCENE Return decrementing points with data.txt'
        "FPOE-13063"       | "62"        | "Serial Number Note Type with data"                                                                                              | "1826"                      | 'Serial Number Note Type with data.xml'                                                                                            | 'Serial Number Note Type with data.txt'
        "FPOE-13063"       | "63"        | "Single Item Discount with Data"                                                                                                 | "8980"                      | 'Single Item Discount with Data.xml'                                                                                               | 'Single Item Discount with Data.txt'
        "FPOE-13063"       | "64"        | "Slice 9 - Competitor Name Note Type SubTotal Discount with Approval"                                                            | "2522"                      | 'Slice 9 - Competitor Name Note Type SubTotal Discount with Approval.xml'                                                          | 'Slice 9 - Competitor Name Note Type SubTotal Discount with Approval.txt'
        "FPOE-13063"       | "65"        | "Slice 9 - Control NoSale with data"                                                                                             | "1826"                      | 'Slice 9 - Control NoSale with data.xml'                                                                                           | 'Slice 9 - Control NoSale with data.txt'
        "FPOE-13063"       | "66"        | "Slice 9 - Control TransactionVoid with data"                                                                                    | "1826"                      | 'Slice 9 - Control TransactionVoid with data.xml'                                                                                  | 'Slice 9 - Control TransactionVoid with data.txt'
        "FPOE-13063"       | "67"        | "Slice 9 - Non Receipted Return with data"                                                                                       | "2522"                      | 'Slice 9 - Non Receipted Return with data.xml'                                                                                     | 'Slice 9 - Non Receipted Return with data.txt'
        "FPOE-13063"       | "68"        | "Slice 9 - SubTotal Discount with Approval"                                                                                      | "8980"                      | 'Slice 9 - SubTotal Discount with Approval.xml'                                                                                    | 'Slice 9 - SubTotal Discount with Approval.txt'
        "FPOE-13063"       | "69"        | "Slice 13 - SCENE Points Earned with data"                                                                                       | "1826"                      | 'Slice 13 - SCENE Points Earned with data.xml'                                                                                     | 'Slice 13 - SCENE Points Earned with data.txt'
        "FPOE-13063"       | "70"        | "Control TransactionVoid Auto Void with data"                                                                                    | "1826"                      | 'Control TransactionVoid Auto Void with data.xml'                                                                                  | 'Control TransactionVoid Auto Void with data.txt'
        "FPOE-13063"       | "71"        | "GiftCertificate and cash Tendered with data"                                                                                    | "1826"                      | 'GiftCertificate and cash Tendered with data.xml'                                                                                  | 'GiftCertificate and cash Tendered with data.txt'
        "FPOE-13063"       | "72"        | "Item and Transaction Tax Exemptions with data"                                                                                  | "2504"                      | 'Item and Transaction Tax Exemptions with data.xml'                                                                                | 'Item and Transaction Tax Exemptions with data.txt'
        "FPOE-13063"       | "73"        | "Non Mech Non Taxable with data"                                                                                                 | "2080"                      | 'Non Mech Non Taxable with data.xml'                                                                                               | 'Non Mech Non Taxable with data.txt'
        "FPOE-13063"       | "74"        | "Non Merch Taxable with data"                                                                                                    | "2080"                      | 'Non Merch Taxable with data.xml'                                                                                                  | 'Non Merch Taxable with data.txt'
        "FPOE-13063"       | "75"        | "Store Promo Tender with Data"                                                                                                   | "2451"                      | 'Store Promo Tender with Data.xml'                                                                                                 | 'Store Promo Tender with Data.txt'
        "FPOE-13063"       | "76"        | "SubTotal Discount with Approval"                                                                                                | "8980"                      | 'SubTotal Discount with Approval.xml'                                                                                              | 'SubTotal Discount with Approval.txt'
        "FPOE-13063"       | "77"        | "SubTotal Discount with Data"                                                                                                    | "8980"                      | 'SubTotal Discount with Data.xml'                                                                                                  | 'SubTotal Discount with Data.txt'
        "FPOE-13063"       | "78"        | "Suspended Transaction with data"                                                                                                | "2218"                      | 'Suspended Transaction with data.xml'                                                                                              | 'Suspended Transaction with data.txt'
        "FPOE-13063"       | "79"        | "System Item Tax Exemption with data"                                                                                            | "8937"                      | 'System Item Tax Exemption with data.xml'                                                                                          | 'System Item Tax Exemption with data.txt'
        "FPOE-13063"       | "80"        | "Tax Override with data"                                                                                                         | "2517"                      | 'Tax Override with data.xml'                                                                                                       | 'Tax Override with data.txt'
        "FPOE-13063"       | "81"        | "Tender Exchange Transaction with data"                                                                                          | "2096"                      | 'Tender Exchange Transaction with data.xml'                                                                                        | 'Tender Exchange Transaction with data.txt'
        "FPOE-13063"       | "82"        | "Tender ExchangeTransaction GC to GC with data"                                                                                  | "2096"                      | 'Tender ExchangeTransaction GC to GC with data.xml'                                                                                | 'Tender ExchangeTransaction GC to GC with data.txt'
        "FPOE-13063"       | "83"        | "Transaction 173"                                                                                                                | "000173"                    | 'Transaction 173.xml'                                                                                                              | 'Transaction 173.txt'
        "FPOE-13063"       | "84"        | "Transaction 174"                                                                                                                | "000174"                    | 'Transaction 174.xml'                                                                                                              | 'Transaction 174.txt'
        "FPOE-13063"       | "85"        | "Transaction 175"                                                                                                                | "000175"                    | 'Transaction 175.xml'                                                                                                              | 'Transaction 175.txt'
        "FPOE-13063"       | "86"        | "Transaction 176"                                                                                                                | "000176"                    | 'Transaction 176.xml'                                                                                                              | 'Transaction 176.txt'
        "FPOE-13063"       | "87"        | "Transaction 177"                                                                                                                | "000177"                    | 'Transaction 177.xml'                                                                                                              | 'Transaction 177.txt'
        "FPOE-13063"       | "88"        | "Two Items One System Tax Exempt One Not with data"                                                                              | "8937"                      | 'Two Items One System Tax Exempt One Not with data.xml'                                                                            | 'Two Items One System Tax Exempt One Not with data.txt'
        "FPOE-13063"       | "89"        | "USD Tendered with data"                                                                                                         | "1826"                      | 'USD Tendered with data.xml'                                                                                                       | 'USD Tendered with data.txt'
        "FPOE-13063"       | "90"        | "Validated Basic Sale with dataa"                                                                                                | "1826"                      | 'Validated Basic Sale with data.xml'                                                                                               | 'Validated Basic Sale with data.txt'
        "EAI-6985"         | "91"        | "CheckingforSpecialcharinCertificateNumbere"                                                                                     | "000455"                    | 'CheckingforSpecialcharinCertificateNumber.xml'                                                                                    | 'CheckingforSpecialcharinCertificateNumber.txt'
        "EAI-6985"         | "92"        | "CheckingforSpecialcharinCustomerExemptionID"                                                                                    | "000455"                    | 'CheckingforSpecialcharinCustomerExemptionID.xml'                                                                                  | 'CheckingforSpecialcharinCustomerExemptionID.txt'
        "EAI-6985"         | "93"        | "CheckingforSpecialcharinGovernmentRegistrationNumber"                                                                           | "000455"                    | 'CheckingforSpecialcharinGovernmentRegistrationNumber.xml'                                                                         | 'CheckingforSpecialcharinGovernmentRegistrationNumber.txt'
        "EAI-6985"         | "94"        | "CheckingforSpecialcharinNativebandNumber"                                                                                       | "000455"                    | 'CheckingforSpecialcharinNativebandNumber.xml'                                                                                     | 'CheckingforSpecialcharinNativebandNumber.txt'
        "EAI-6985"         | "95"        | "CheckingforSpecialcharinName"                                                                                                   | "003098"                    | 'CheckingforSpecialcharinName.xml'                                                                                                 | 'CheckingforSpecialcharinName.txt'











    }

}
