@REM File: caldc-env.bat
@REM Version: 0.1.1
@REM Date: 19-Dec 2014
@REM Author: Alex Russell

SET "_NODE=IBN1"
@REM SET "_NODE=IBN2"
SET "_SERVER=IBS1"
@REM SET "_SERVER=IBS1.1_FGL"
@REM SET "_SERVER=IBS1.2_MKS"
SET "_ENVN="
SET "_INST="
SET "_HOSTNAME_=-10.100.116.52"
